export const GET_HEADER = "GET_HEADER";
export const GET_STANDARD_PAGES = "GET_STANDARD_PAGES";
export const GET_BLOCK_CONTENTS = "GET_BLOCK_CONTENTS";
export const GET_GRID_CONTENTS = "GET_GRID_CONTENTS";